### ISSUE TITLE
Add LLVM to the repository 

### ISSUE THREAD

**Issue by Arkosake** [xavatar/repo.xavatar.com#1]
Good morning. Please consider adding LLVM to the repository, because today Manjaro Linux had updates from version 9.0.1 to 10.0.0 and the entire graphics system has failed. The only salvation was to throw the drivers out of the repository and install those delivered with the system. Greetings Arkosake

**Comment by xavatar** [comment]
Hello,
Sorry for my english, i'm french. 
I did the update and I didn’t have a problem...

But yes, i'm going to add LLVM to the repo.

**Comment by xavatar** [comment]
LLVM added.
